### ISSUE TITLE
CADMatch: Images for Result and Intermediate Result

### ISSUE THREAD

**Issue by renzobazan96** [roboception/rc_reason_clients_ros#1]
Hi, 
I have been using the CAD Match reason client for ROS which is working very well. I wanted to ask if there is already a way of getting the "Intermediate Result" and "Result" images like the web GUI for CAD Match for ROS.

**Comment by flixr** [comment]
Unfortunately not, those are only downscaled and jpeg compressed visualization images for the WebGUI.
What would you actually like to have available on the ROS side?
One possibility would be to load the CADModel into RViz as a mesh and display that there.

**Comment by renzobazan96** [comment]
Yes, that would  help the user verify if the results are reasonable. Is there already a way of dynamically changing the CADmatch parameters with ROS?

**Comment by flixr** [comment]
You can open a new feature request about showing the CADModel as RViz marker mesh.
Can't promise a timeline for this feature though.

Regarding parameters, all should be automatically available via dynamic reconfigure and some additional ones for publishing results:
https://github.com/roboception/rc_reason_clients_ros/tree/master/rc_reason_clients#rc_cadmatch_client

**Comment by renzobazan96** [comment]
Ok thanks, I will open the request and will use the GUI to visualize the CAD in the meantime. 
Could you include the parameters and services avaiable to ROS similar to this README: https://github.com/roboception/rc_visard_ros/blob/master/rc_tagdetect_client/README.md#configuration 
I was a little confuse about the  "CAD Match Services" link in README because it refers to many REST-API services not availble to ROS

**Comment by flixr** [comment]
Thanks for your feedback!

For the services we can indeed add this information to the README.

However I'm a bit reluctant to document the parameters in the README, as the whole point of this new implementation was to NOT specify the available parameters (and their min/max values) at compile time via a cfg file and instead fetch them from our API and provide them exactly as they are on the device (rc_visard or rc_cube) with the actually used firmware version to not have inaccurate/stale information in the client node and [README](https://github.com/roboception/rc_reason_clients_ros/tree/master/rc_reason_clients#running).

Any suggestions on how to make this more clear and document this better?

**Comment by renzobazan96** [comment]
I understand, then for the parameters I would say it is ok like that. Thanks for the help!
